language: node_js
node_js:
- '7'
services:
  - redis-server
  deploy:
    provider: npm
    email: kian.peymani@gmail.com
    api_key:
      secure: cSSUaP4V7PutZRkRI9U9/JJ0YqvmToP/D8oEjMRwWH0eQK7+Wx4Ra+NB6glTkBMVoDHDTEgtO56VpWnmI6dVku5/O7DzmV4VUo/Khh4tBY8UTLM51hH5GAl+ac8BAbWuMhzKnkxWdNDTD6bGNBjGlLIC5LgRARphW6ZTJ9A7nbN25/4ve2kx6LSgk+SsizWo95ACQ6hdGcHIfTMwygq1moXRX/nkZxbVTphQ$
    on:
      repo: node-xyz/xyz-core
      branch: master
